### ISSUE TITLE
Does this allow me to let banned users see the forum (albeit not post in it)?

### ISSUE THREAD

**Issue by gillerby** [Xon/XenForo2-BanGroups#1]
By default, banned users can do nothing at all.

If I install this, would I be able to instead add banned users (via the "ban this user" button) to personalized groups instead where I can set my own permissions?

Basically, i want banned users to be able to see the forum still, no matter how they are banned.

**Comment by Xon** [comment]
This add-on just adds a user group for styling purposes.
